[package]
name = "premise"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "3.0.0"
indicatif = {version="0.17.8", features = ["rayon"]}
clap = { version = "4.0", features = ["derive"] }
rayon = "1.7.0"
itertools = "0.14.0"
anyhow = "1.0.98"
flate2 = "1.1.2"
chrono = "0.4.42"
haystackfm = { version = "0.3.0", features = ["cpu"] }
bincode = "1"
dashmap = "6.1.0"
num = "0.4.3"
tiny_http = "0.12"

[dev-dependencies]
tempfile = "3"
ureq = { version = "2", default-features = false }
savefile = "0.20.2"
criterion = { version = "0.5", features = ["html_reports"] }

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.13", features = ["flamegraph", "criterion", "protobuf-codec"] }

[[bench]]
name = "alignment"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
debug = true

[profile.bench]
lto = "fat"
codegen-units = 1
debug = true
